apps:
  coffee:
    image: nginxdemos/hello:plain-text
    replicas: 2
  tea:
    image: nginxdemos/hello:plain-text
    replicas: 3

ingress:
  name: cafe-ingress
  rules:
  - host: cafe.example.com
    paths:
    - path: /tea
      app: tea
    - path: /coffee
      app: coffee
  tlsSecrets:
  - name: cafe-tls-secret
    crtPath: ${TLS_CAFE_CERT}
    key: ${TLS_CAFE_KEY}