apps:
  coffee:
    image: nginxdemos/hello:plain-text
    replicas: 2
  tea:
    image: nginxdemos/hello:plain-text
    replicas: 3
  whiskey:
    image: nginxdemos/hello:plain-text
    replicas: 2
  vodka:
    image: nginxdemos/hello:plain-text
    replicas: 3

ingress:
  name: beverage-ingress
  rules:
  - host: cafe.example.com
    paths:
    - path: /tea
      app: tea
    - path: /coffee
      app: coffee
  - host: bar.example.com
    paths:
    - path: /vodka
      app: vodka
    - path: /whiskey
      app: whiskey
  tlsSecrets:
  - name: cafe-tls-secret
    crt: ${TLS_CAFE_CERT}
    key: ${TLS_CAFE_KEY}
  - name: bar-tls-secret
    crt: ${BAR_CRT_PATH}
    key: ${BAR_KEY_PATH}
