#!/bin/bash

#list the python files that are staged for commit
changed_py_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')

if [ -n "$changed_py_files" ]; then
  echo "Python files changed — running Bandit..."

  bandit -r . -f csv -o bandit_report.csv

  if [ $? -eq 0 ]; then
    echo "Bandit scan completed — results saved to bandit_report.csv"
  else
    echo "Bandit found issues. See bandit_report.csv"
  fi
else
  echo "No Python files changed. Skipping Bandit scan."
fi
