# .github/workflows/bandit.yml
name: Bandit scan & commit report

on:
  push:
    # only trigger when at least one .py file changes
    paths:
      - '**/*.py'

permissions:
  contents: write     # allow the action to push back

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code & keep token
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Point Git at our committed hook
        run: git config core.hooksPath .github/hooks

      - name: Make hook executable
        run: chmod +x .github/hooks/pre-commit

      - name: Run pre-commit (full project scan)
        run: .github/hooks/pre-commit
        continue-on-error: true

      - name: Move Bandit report into results folder
        run: |
          mkdir -p KubeSec-master/results
          mv bandit_report.csv KubeSec-master/results/

      - name: Auto-commit updated report
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Bandit report"
          file_pattern: "KubeSec-master/results/bandit_report.csv"
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
