name: Bandit security scan

on:
  push:
    # fire only when a .py file changes, but ignore updates under results/
    paths:
      - '**/*.py'
    paths-ignore:
      - 'KubeSec-master/results/**'

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run full Bandit scan
        run: |
          mkdir -p KubeSec-master/results
          bandit -r . -f csv -o KubeSec-master/results/bandit_report.csv

      - name: Commit Bandit report back to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: update Bandit report for ${{ github.sha }}"
          file_pattern: "KubeSec-master/results/bandit_report.csv"
          branch: main
