name: Run Fuzzer

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Change to KubeSec-master and install dependencies
        working-directory: KubeSec-master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fuzz tests and capture output
        working-directory: KubeSec-master
        run: |
          echo "Running fuzz.py..." > fuzz_output.txt
          python fuzz.py >> fuzz_output.txt
          echo "Finished running fuzz.py." >> fuzz_output.txt

      - name: Display contents of fuzz_output.txt
        run: |
          echo "Contents of fuzz_output.txt:"
          cat KubeSec-master/fuzz_output.txt

      - name: Upload fuzz output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-output
          path: KubeSec-master/fuzz_output.txt
