name: Run Fuzzer

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  fuzz-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Change to KubeSec-master and install dependencies
        working-directory: KubeSec-master
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fuzz tests
        working-directory: KubeSec-master
        run: |
          python fuzz.py
